#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2025 DFT project (http://www.firmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

---
- name: DFT - Install Kicad & Horizon
  apt:
       name={{item}}
       state=latest
       install_recommends=no
  with_items:
       - kicad-doc-fr
       - horizon-eda
       - kicad
       - kicad-demos
       - kicad-libraries
       - kicad-footprints
       - kicad-libraries
       - kicad-packages3d
       - kicad-symbols
       - kicad-templates
       - pcb-rnd-io-alien
       - pcb-rnd
       - turbocase
       - veroroute
       - veroroute-data
       - kicad-footprints


