#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.debianfirmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
# Debian Firmware Toolkit is the new name of Linux Firmware From Scratch
# Copyright 2014 LFFS project (http://www.linuxfirmwarefromscratch.org).
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

#
# Include the list of specific tasks. Tasks are separated into different
# files, one file per functionnality.
#

# -------------------------------------------------------------------------------------------------
# Create the reprepro group
- name: Create the reprepro group
  group: name={{ dft_debian_repository_user_definition.group }}
         state=present

# Add the user 'reprepro' with a bash shell, appending the group reprepro and
# {{ dft_debian_repository_web_server_definition.group }} to the user's groups
- name: Create the reprepro user
  user: name={{ dft_debian_repository_user_definition.username }}
        shell={{ dft_debian_repository_user_definition.shell }}
        home={{ dft_debian_repository_user_definition.home_dir }}
        group={{ dft_debian_repository_user_definition.group }}
        groups={{ dft_debian_repository_web_server_definition.group }}
        append=yes

# Create the reprepro script directory
- name: DFT - Create reprepro script directory
  file: path={{ dft_debian_repository_user_definition.home_dir }}/bin
        state=directory
        recurse=yes
        owner={{ dft_debian_repository_user_definition.username }}
        group={{ dft_debian_repository_user_definition.group }}
        mode="0755"

# Instanciate the options template file
- name: DFT - Copy reprepro_import_packages script template
  template: src=reprepro_import_packages.j2
            dest={{ dft_debian_repository_user_definition.home_dir }}/bin/reprepro_import_packages
            owner={{ dft_debian_repository_user_definition.username }}
            group={{ dft_debian_repository_user_definition.group }}
            mode="0755"

# -------------------------------------------------------------------------------------------------
# Create the repositories subdirectories
- name: DFT - Create repository directories
  file: path={{ dft_debian_repository_directory }}/{{ item[1].base_dir }}/{{ item[0] }}
        state=directory
        recurse=yes
        owner={{ dft_debian_repository_web_server_definition.group }}
        group={{ dft_debian_repository_web_server_definition.group }}
        mode="0775"
  with_nested:
    - ['conf', 'db', 'dists', 'logs', 'indices', 'override', 'pool', 'project', 'tmp' ]
    - "{{ dft_debian_repository_configuration }}"

# Create the deb override files
- name: DFT - Create override files
  file: path={{ dft_debian_repository_directory }}/{{ item.base_dir }}/conf/{{ item.deb_override }}
        state=touch
        owner={{ dft_debian_repository_web_server_definition.group }}
        group={{ dft_debian_repository_web_server_definition.group }}
        mode="0775"
  when: "{{ item.deb_override }} is defined"
  with_items:
    - "{{ dft_debian_repository_configuration }}"

# Create the dsc override files
- name: DFT - Create override files
  file: path={{ dft_debian_repository_directory }}/{{ item.base_dir }}/conf/{{ item.dsc_override }}
        state=touch
        owner={{ dft_debian_repository_web_server_definition.group }}
        group={{ dft_debian_repository_web_server_definition.group }}
        mode="0775"
  when: "{{ item.dsc_override }} is defined"
  with_items:
    - "{{ dft_debian_repository_configuration }}"

# Incoming is created alone because of the different mode
- name: DFT - Create repository incoming directory
  file: path={{ dft_debian_repository_directory }}/{{ item.base_dir }}/incoming
        state=directory
        recurse=yes
        owner={{ dft_debian_repository_web_server_definition.group }}
        group={{ dft_debian_repository_web_server_definition.group }}
        mode="0775"
  with_items:
    - "{{ dft_debian_repository_configuration }}"

# Instanciate the distributions template file
- name: DFT - Copy distributions template
  template: src=distributions.j2
            dest={{ dft_debian_repository_directory }}/{{ item.base_dir }}/conf/distributions
            owner={{ dft_debian_repository_web_server_definition.group }}
            group={{ dft_debian_repository_web_server_definition.group }}
            mode="0644"
  with_items:
    - "{{ dft_debian_repository_configuration }}"

# Instanciate the options template file
- name: DFT - Copy options template
  template: src=options.j2
            dest={{ dft_debian_repository_directory }}/{{ item.base_dir }}/conf/options
            owner={{ dft_debian_repository_web_server_definition.group }}
            group={{ dft_debian_repository_web_server_definition.group }}
            mode="0644"
  with_items:
    - "{{ dft_debian_repository_configuration }}"

# Instanciate the incoming template file
- name: DFT - Copy incoming template
  template: src=incoming.j2
            dest={{ dft_debian_repository_directory }}/{{ item.base_dir }}/conf/incoming
            owner={{ dft_debian_repository_web_server_definition.group }}
            group={{ dft_debian_repository_web_server_definition.group }}
            mode="0644"
  with_items:
    - "{{ dft_debian_repository_configuration }}"

# -------------------------------------------------------------------------------------------------
# Add processincoming script cron table for user reprepro. Scheduled every hour by default
- cron: name="Repository update"
        month={{ dft_debian_repository_cron_definition.month }}
        weekday={{ dft_debian_repository_cron_definition.weekday }}
        day={{ dft_debian_repository_cron_definition.day }}
        hour={{ dft_debian_repository_cron_definition.hour }}
        minute={{ dft_debian_repository_cron_definition.minute }}
        user="{{ dft_debian_repository_user_definition.username }}"
        job="cd {{ dft_debian_repository_user_definition.home_dir }} && {{ dft_debian_repository_user_definition.home_dir }}/bin/reprepro_import_packages"

# TODO generate apache vhost
# TODO generate gpg keys
