#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.debianfirmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
# Debian Firmware Toolkit is the new name of Linux Firmware From Scratch
# Copyright 2014 LFFS project (http://www.linuxfirmwarefromscratch.org).
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

# Default hostname to set if not ovrriden in project variables
dft_hostname: "dft-default"


# Default locales to configure if not ovrriden in project variables
dft_locales:
  # Default behavior is to considr that ocl should be installed, thus no need to add state parameter
  - { name: "en_GB.UTF-8" }
  # Nonetheless it can be defined to present
  - { name: "fr_FR.UTF-8" , state: "present" }
  # Set it to absent to ensure a locale is not installed
  - { name: "nl_NL.UTF-8" , state: "absent" }


# Default timezone to configure if not ovrriden in project variables
dft_timezone: "Etc/UTC"


# Defines optionaly a password for root account (if this variable is defined).
# If not defined a random pssword is set
# dft_root_password: "{{ 'root' | password_hash('sha512') }}"

# Defines the list of groups to create if absent
# dft_groups:
#  - { name: "dft" }

# Defines the list of users to create. By default, create a user named dft
# and put it into sudo group.
#
# The password field contains the plain text password (which is evil ! but sometime useful)
# The password_hash contains the hahed value of the password. This variable has priority over
# plain text value (if both are defined).
# dft_users:
#  - { name: "dft" ,
#      password: "dft" ,
#      password_hash: "$6$2P36HIipn2AWBkoQ$o95Ooh0EodX8Rt9LFUW4zQNBYuIyu.i50THN9JWrKwPbnMjJMV1c97zX3HiBZ/CZYLQtxTlfDRj/TLDpQsIWp." ,
#      createhome: True ,
#      groups: 'sudo' ,
#      group: 'sudo' ,
#      shell: '/bin/bash'
#     generate_ssh_key: 'no',
#     ssh_key_file: "dft.pub" ,
#     ssh_key_options: "options_to_set",
#     ssh_keys_are_exclusive: True
#    }
