#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.debianfirmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
# Debian Firmware Toolkit is the new name of Linux Firmware From Scratch
# Copyright 2014 LFFS project (http://www.linuxfirmwarefromscratch.org).
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2016 DFT project (http://www.debianfirmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
# Debian Firmware Toolkit is the new name of Linux Firmware From Scratch
# Copyright 2014 LFFS project (http://www.linuxfirmwarefromscratch.org).
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

# This variables is the base directory for the repositories, everything will be created under
# this path
dft_debian_repository_directory: /srv/debian-repositories

# This variable is a list of repository configurations. Each item in the list is a repo
dft_debian_repository_configuration:
  - origin: DFT
    base_dir: debian
    label: DFT Test repo
    suite: testing
    codename: stretch
    # version: 9.0
    architectures: i386 amd64 ppc64 source
    components: main
    udeb_components: main
    log: dft.log
    description: DFT test repository (you should change this to your real configuration)
    # deb_override: override.stretch
    # dsc_override: override.stretch
    # sign_with: default
    # udeb_override:
    # dsc_override:
    # deb_indices: Packages Release . .gz .bz2
    # udeb_indices: Packages . .gz .bz2
    # dsc_indices: Sources Release .gz .bz2
    # contents: Sources Release .gz .bz2
    # The allow variable is a list of rules to output to the Allow section
    allow:
      - testing>stretch stretch

  - origin: DFT-security
    base_dir: debian-security
    label: DFT Test repo security
    suite: testing
    codename: stretch
    # version: 9.0
    architectures: i386 amd64 ppc64 source
    components: main
    udeb_components: main
    log: dft-security.log
    description: DFT test repository (you should change this to your real configuration)
    # deb_override: override.stretch
    # dsc_override: override.stretch
    # sign_with: default

# reprepro role variables definition
#
dft_debian_repository_user_definition:
  reprepro_user_username: reprepro
  reprepro_user_group: reprepro
  reprepro_user_home_dir: /home/reprepro/
  reprepro_user_shell: /bin/bash

# Parameters of the cron job. Cron is running the reprepro_import_packages script
dft_debian_repository_cron_definition:
  reprepro_cron_month: "*"
  reprepro_cron_weekday: "*"
  reprepro_cron_day: "*"
  reprepro_cron_hour: "*"
  reprepro_cron_minute: "0"

dft_debian_repository_web_server_definition:
  group: "www-data"
