#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2017 DFT project (http://www.debianfirmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
# Debian Firmware Toolkit is the new name of Linux Firmware From Scratch
# Copyright 2014 LFFS project (http://www.linuxfirmwarefromscratch.org).
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

- name : DFT - Add pinebook module loading configuration files
  copy: src=files/load-pinebook-{{ item }}.conf
        dest=/etc/modules_load.d/pinebook-{{ item }}.conf
        mode=0644
        owner=root
        group=root
  with_items:
    - bluetooth
    - dispo
    - hall
    - wifi

- name : DFT - Add pinebook module probing configuration files
  copy: src=files/probe-pinebook-{{ item }}.conf
        dest=/etc/modprobe.d/pinebook-{{ item }}.conf
        mode=0644
        owner=root
        group=root
  with_items:
    - wifi
